name: Mandir Check
on:
   push:
      branches: [ main ]
jobs:
    check-mandir:
      runs-on: ubuntu-latest
      steps:
         -uses: actions/checkout@v4
         -name: Mandir dekhna
            run: |
                echo "Radhe Radhe Shri Harivansh"
                cat mandir.txt
